### ISSUE TITLE
Code Review: Max Wilkinson, 26551623

### ISSUE THREAD

**Issue by mwilko** [JaxkDev-UoL/CMP1902M-Assignment1#1]
Your project seems to not have any errors and matches criteria excellently, There is also great use of comments overall to explain the algorithms used, requirements as well as referencing to where you found information about the shuffling algorithms. 

To improve the efficiency and portability of the project you could implement a way for the user to choose what they want to do. For example ask if they want to shuffle the pack of cards using the Fisher-Yates or Riffle shuffling and whether they want to deal one card or multiple. 

To make portability of the project  easier, both of these Console.WriteLine messages could be put into the dealCard methods.

#Console.WriteLine("-- Deal Single --");
#Console.WriteLine("-- Deal Multiple --");

You could add the range validations of suits and values which you have specified into the 'Card' constructor into the property's set methods. This would ensure you have set validations for the set methods instead of just encapsulating them as private.
Is there any need to specify Value and Suit in the exception message as its just displaying the string?
        
    #public Card(int Value, int Suit) {
            #if(Value > 13 || Value < 1) {
                #throw new ArgumentOutOfRangeException("Value", "Value must be in the range 1-13 inclusive.");
            #}
            #if(Suit > 4 || Suit < 1) {
                #throw new ArgumentOutOfRangeException("Suit", "Suit must be in the range 1-4 inclusive.");
            #}
            #this.Value = Value;
            #this.Suit = Suit;
     #}

Student: Max Wilkinson        ID: 26551623

**Comment by mwilko** [comment]
Adding to this code review, your code has great error handling as it is, both type and range validation is present, well done.

**Comment by JaxkDev** [comment]
Hi Max,

Thanks for the review!

I have taken into consideration the user input for improved efficiency and portability and created a testing menu as to where the user can execute all functionality of the program.

The console messages for dealing has also been put into their respective functions now.

And I have both moved the validation ifs into their respective variable setters and created a new `ValueException` class to simplify all error handling in the entire program not just at that point.

Thanks for the review!
