### ISSUE TITLE
code review: Alfie Holman 25798788

### ISSUE THREAD

**Issue by alfieH0** [JaxkDev-UoL/CMP1902M-Assignment1#4]
overall very good coding and commenting on the program that makes it easy to understand however I would suggest adding a menu in the testing class this would allow the user to more easily switch between the shuffling types and also allow them to more easily pick how many cards they would like it to deal but overall a very good program

**Comment by JaxkDev** [comment]
Thanks Alfie for the review,

I have looked into the menu for testing class and have implemented that, thanks!
