### ISSUE TITLE
Derrick Ntim, 26411073

### ISSUE THREAD

**Issue by dnzntm** [JaxkDev-UoL/CMP1902M-Assignment1#5]
This is a very well-written code throughout the entire project, I can hardly find an area to improve however for the card class I would consider: 

Using constants for the minimum and maximum values of Value and Suit instead of hardcoding them in the getters and setters. This would make the code easier to read and maintain, and reduce the risk of errors caused by inconsistent values.

Add validation for the input values in the constructor to ensure they are within the valid ranges.

https://github.com/JaxkDev-UoL/CMP1902M-Assignment1/blob/main/CMP1903M%20A01%202223/Card.cs

Your ValueException class is very well-written as well, the only improvement I can think of making would be: 

To use constants: Instead of hard-coding the minimum and maximum values for Value and Suit in the validation code, I believe this would be better to use constants. This would make it easier to change the valid ranges in the future if necessary, and would also make the code more readable.

https://github.com/JaxkDev-UoL/CMP1902M-Assignment1/blob/main/CMP1903M%20A01%202223/ValueException.cs

Another improvement I would think of adding would be to your Pack class where inthe shuffleCardPack method, the typeOfShuffle parameter is checked for validity, but the error message does not indicate the actual value of the parameter that caused the error. It would be better to include the actual value in the error message.

https://github.com/JaxkDev-UoL/CMP1902M-Assignment1/blob/main/CMP1903M%20A01%202223/Pack.cs

Your error handling is done brilliantly and the code runs very smoothly looping the code until I input the correct values.

![2023-03-09 (5)](https://user-images.githubusercontent.com/126176909/224026941-a8b19b9d-7d33-446e-8d6b-69133a41be78.png)

Overall these are very minor suggestions and are mainly pushed towards improving the readability of the code, very good project.

Derrick Ntim, 26411073

**Comment by JaxkDev** [comment]
Thanks for the review Derrick,

I have taken all of the above into consideration and fortunately it's only readability suggestions that have been made, therefor with the time constraint I'll have to leave most of them out.

But thank you so much for the review 👍
